compressionLevel: mixed

defaultSemverRangePrefix: "~"

enableGlobalCache: true

enableTimers: true

nodeLinker: pnpm

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-outdated.cjs
    spec: "https://mskelton.dev/yarn-outdated/v3"

pnpMode: strict

progressBarStyle: jack

tsEnableAutoTypes: false

yarnPath: .yarn/releases/yarn-4.12.0.cjs
