compressionLevel: mixed

defaultSemverRangePrefix: ^

enableGlobalCache: true

enableTimers: true

nodeLinker: pnpm

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-outdated.cjs
    spec: "https://mskelton.dev/yarn-outdated/v3"

tsEnableAutoTypes: false

pnpMode: strict

progressBarStyle: jack

yarnPath: .yarn/releases/yarn-4.3.1.cjs
