compressionLevel: mixed

defaultSemverRangePrefix: ^

enableGlobalCache: false

enableTimers: true

nmSelfReferences: false

nodeLinker: pnpm
winLinkType: symlinks

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-outdated.cjs
    spec: "https://mskelton.dev/yarn-outdated/v3"

pnpFallbackMode: all

tsEnableAutoTypes: false

yarnPath: .yarn/releases/yarn-4.3.1.cjs
