compressionLevel: mixed

defaultSemverRangePrefix: ^

enableGlobalCache: true

enableTimers: true

nmSelfReferences: false

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-outdated.cjs
    spec: "https://mskelton.dev/yarn-outdated/v3"

pnpFallbackMode: all

tsEnableAutoTypes: true

yarnPath: .yarn/releases/yarn-4.3.1.cjs
