compressionLevel: mixed

enableGlobalCache: true

nodeLinker: pnpm

defaultSemverRangePrefix: "^"
enableTimers: true
nmSelfReferences: false
tsEnableAutoTypes: true

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-outdated.cjs
    spec: "https://mskelton.dev/yarn-outdated/v3"

yarnPath: .yarn/releases/yarn-4.1.1.cjs
