name: Build

on:
  push:
    branches:
      - develop
      - main
      - next

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        node: [22]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: yarn

      # Turn off windows-defender for this folder to speed up compile
      - if: runner.os == 'Windows'
        name: windows-defender
        run: powershell -Command Add-MpPreference -ExclusionPath "."

      - name: Set PNPM Store Directory
        shell: pwsh
        run: |
          $env:PNPM_HOME = "$($env:GITHUB_WORKSPACE)\.pnpm-store"
          $env:PATH += ";$env:PNPM_HOME"
          echo "PNPM_HOME=$env:PNPM_HOME" >> $env:GITHUB_ENV
          echo "PATH=$env:PATH" >> $env:GITHUB_ENV

      - name: Configure Yarn
        run: |
          echo "nodeLinker: pnpm" >> .yarnrc.yml

      - name: install
        run: yarn install --network-timeout 1000000

      - name: build
        run: yarn xy build

      - name: cycle
        run: yarn cycle
