name: Build

on:
  push:
    branches:
      - main
      - beta

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Git Version
        uses: codacy/git-version@2.2.0
        with:
          release-branch: main
          dev-branch: beta
      - name: install
        run: yarn install
      - name: build
        run: yarn build
